        // stage("Checkout"){
        //     steps{
        //         checkout scm
        //     }
        // }

        // stage("Cloning Git"){
        //     steps {

        //     }
        // }


        // stage("test"){
        //     steps{
        //         sh 'npm test'
        //     }
        // }

        // stage("build"){
        //     steps{
        //         sh ''
        //     }
        // }


pipeline {
    agent any
    stages {

        stage("Install dependencies"){
            steps{
                dir('backend') { // Change to backend directory
                    sh 'sudo npm install'
                }
            }
        }

        stage("Start App"){
            steps {
                dir('backend') { // Change to backend directory
                    sh 'npm start'
                }
            }
        }
    }
}