pipeline {
    agent any
    stages {

        stage("Install dependencies"){
            steps{
                dir('backend') { // Change to backend directory
                    sh 'npm install'
                }
            }
        }

        stage("Build App"){
            steps {
                dir('backend') { // Change to backend directory
                    // Only for demo purposes, to "build". With npm start -> build runs infinite.
                    sh 'npm run build'
                }
            }
        }

        stage("Build Image"){
            steps{
                dir('backend') { // Change to backend directory
                    sh 'docker build -t e-com-backend .'                    
                }
            }
        }

        stage("Docker Push"){
            steps {
                sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
                sh 'docker tag e-com-backend makocp/e-com-backend'
                sh 'docker push makocp/e-com-backend'
                sh 'docker logout'
            }
        }

        stage("Deploy to GKE"){
            steps {
                sh 'gcloud container clusters get-credentials ecom-backend-cluster --zone us-central1-a --project e-com-project-408719'
                sh "kubectl create deployment ecom-backend-${env.BUILD_NUMBER} --image=makocp/e-com-backend:${env.BUILD_NUMBER} --port=3000"
                sh "kubectl expose deployment ecom-backend-${env.BUILD_NUMBER} --name=ecom-backend-service-${env.BUILD_NUMBER} --type=LoadBalancer --port=3000"
            }
        }
    }
}
